# Generated by Django 3.2 on 2022-08-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('description', models.TextField(verbose_name='category description')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='category code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('description', models.TextField(verbose_name='description')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='product code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('quantity', models.IntegerField(default=0, verbose_name='product quantity')),
                ('brand', models.CharField(max_length=255, verbose_name='product brand')),
                ('is_available', models.BooleanField(default=True, verbose_name='product availability')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
