# Generated by Django 3.2 on 2022-09-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220927_0742'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'specification')},
        ),
    ]
