# Generated by Django 3.2 on 2022-09-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_productspecification_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='base.specificationoption'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='base.specification'),
        ),
    ]
