# Generated by Django 3.2 on 2022-11-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220927_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processed'), (3, 'Delivered')], default=1, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_specifications',
            field=models.ManyToManyField(blank=True, related_name='specifications', through='base.ProductSpecification', to='base.SpecificationOption'),
        ),
        migrations.CreateModel(
            name='NPDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_city', to='base.city')),
            ],
        ),
    ]
